// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNIZH6y__9p4unWtiTOBAwJTCTy_nRDo8',
    appId: '1:687314180313:web:df825602383da34a0186c8',
    messagingSenderId: '687314180313',
    projectId: 'csci6180-project',
    authDomain: 'csci6180-project.firebaseapp.com',
    storageBucket: 'csci6180-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIKs2VEWxVxlJmNGlyzbVn8kUcxXeaJcg',
    appId: '1:687314180313:android:c396e68bb40b51b70186c8',
    messagingSenderId: '687314180313',
    projectId: 'csci6180-project',
    storageBucket: 'csci6180-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRhhqarJW4JQV2Y3NLvs6nR9W8RKwTDuA',
    appId: '1:687314180313:ios:23ff2d46673eb2ee0186c8',
    messagingSenderId: '687314180313',
    projectId: 'csci6180-project',
    storageBucket: 'csci6180-project.appspot.com',
    iosBundleId: 'com.example.theFridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRhhqarJW4JQV2Y3NLvs6nR9W8RKwTDuA',
    appId: '1:687314180313:ios:d529ac379f1b9da40186c8',
    messagingSenderId: '687314180313',
    projectId: 'csci6180-project',
    storageBucket: 'csci6180-project.appspot.com',
    iosBundleId: 'com.example.theFridge.RunnerTests',
  );
}
